name: Test
on: workflow_dispatch # manual 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository Code # Клонирование репозитория 
        uses: actions/checkout@v5
        
      - name : Install depandencies # Установка зависимостей Python
        run: |
          python -m pip install --upgrade pip

      - name : tests
        run: |
          python manage.py test
