name: Test
on: workflow_dispatch # manual 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Repository Code # Клонирование репозитория 
        uses: actions/checkout@v5
        
      - name : Install depandencies # Установка зависимостей Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name : Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate
